# Generated by Django 4.2.30 on 2026-08-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('cover_image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('vinyl', 'Standard Vinyl'), ('special_edition', 'Special Edition'), ('coloured_vinyl', 'Coloured Vinyl')], default='vinyl', max_length=20)),
                ('colour_variant', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('tracklist', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
