# Generated by Django 4.2.30 on 2026-08-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='deezer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
