# Generated by Django 4.2.30 on 2026-08-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_deezer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
