# Generated by Django 4.2.30 on 2026-08-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='featured_reason',
            field=models.TextField(blank=True),
        ),
    ]
